version: '3'

services:
  web:
    container_name: docker_rails
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      BUNDLE_APP_CONFIG: ${DOCKER_APP_ROOT}/.bundle
    volumes:
      - ./:${DOCKER_APP_ROOT}
    ports:
      - 3000:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
  db:
    image: mysql:5.7
    container_name: docker_rails_mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_DATABASE_NAME}
      MYSQL_USER: ${APP_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${APP_DATABASE_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
    - 33060:3306
